const phrases = [
  "The innovative spirit of New Orleans residents working together to address climate challenges.",
  "The city's strong commitment to sustainable urban development and green infrastructure.",
  "The increasing number of community-led environmental initiatives and grassroots organizations.",
  "The resilience of the people who continue to rebuild and strengthen the city's defenses against climate impacts.",
  "The growing awareness and education about climate change among young people in New Orleans.",
  "The integration of renewable energy sources in new building projects across the city.",
  "The city's rich cultural heritage and how it inspires creative solutions to environmental issues.",
  "The successful restoration of wetlands around New Orleans, which helps protect against flooding.",
  "The support for local businesses that prioritize eco-friendly practices and products.",
  "The collaboration between local government and environmental groups to create sustainable policies.",
  "The increasing presence of green spaces and community gardens throughout the city.",
  "The dedication to preserving and enhancing New Orleans' unique biodiversity and natural habitats.",
  "The role of innovative technology in improving the city's infrastructure to handle climate impacts.",
  "The cultural events and festivals that raise awareness about environmental issues and promote sustainability.",
  "The growth of eco-tourism in New Orleans, which emphasizes the importance of conservation and responsible travel.",
  "The active involvement of local schools in environmental education and sustainability projects.",
  "The emergence of new green technologies and practices in the city's building and construction industry.",
  "The sense of community and solidarity that drives collective action toward a more sustainable future.",
  "The resilience of New Orleans' historic architecture being retrofitted to withstand climate-related challenges.",
  "The efforts to clean up and revitalize the city's waterways and urban landscapes.",
  "The support for policies that aim to reduce greenhouse gas emissions and enhance climate resilience.",
  "The presence of strong, dedicated leaders advocating for climate action and environmental justice.",
  "The collaborative projects between universities and local organizations to address climate issues creatively.",
  "The success stories of local conservation projects making a tangible difference in the community.",
  "The way traditional New Orleans music and arts are used to promote environmental awareness and action.",
  "The commitment of local governments to improving public transportation options and reducing traffic emissions.",
  "The expansion of green roofs and energy-efficient buildings in urban areas.",
  "The growing movement towards zero-waste practices and recycling programs in the city.",
  "The enthusiasm and creativity of local youth engaged in climate activism and environmental stewardship.",
  "The dedication to building stronger, more resilient infrastructure to protect against extreme weather events.",
  "The collaborative efforts to improve the city's climate resilience through community engagement and planning.",
  "The role of local artists and creatives in raising awareness and inspiring action on climate issues.",
  "The partnerships between New Orleans and other cities to share best practices for climate adaptation.",
  "The progress made in restoring and conserving New Orleans' natural landscapes and ecosystems.",
  "The community spirit and determination to overcome challenges and build a sustainable future.",
  "The integration of climate resilience into urban planning and development projects.",
  "The growing presence of climate-focused research and innovation in local institutions.",
  "The ways in which traditional knowledge and practices are being incorporated into modern climate solutions.",
  "The support for green initiatives and policies at the state and local government levels.",
  "The efforts to make New Orleans a model city for climate adaptation and sustainable living.",
  "The dedication of local activists and volunteers working tirelessly to protect the environment.",
  "The increasing investment in renewable energy projects and green technology startups.",
  "The sense of hope and optimism that drives collective action towards a better climate future for New Orleans.",
];
